### ISSUE TITLE
Game crash after launcher

### ISSUE THREAD

**Issue by Samnotabletoopenthelauncher** [Songs-of-War/Songs-of-War-Launcher#87]
```
Error: spawn /Users/rubenmillo/Library/Application Support/.songsofwar/runtime/x64/Contents/Home/bin/java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

---

Songs of War Game 1.10.5
Electron 11.2.3
darwin 20.1.0
Locale: de

**Comment by eDexiam** [comment]
Mac problems will get reviewed by @forkpoweroutlet

**Comment by forkpoweroutlet** [comment]
@Samnotabletoopenthelauncher A similar issue arose with another person in the past. If it's any help, let me outline what succeeded for that particular user:

1. Use "Go -> Go to Folder" to navigate to the `~/Library/Application Support/.songsofwar/runtime/x64` directory.
2. There, try to find a file called `jre.bundle`.
3. Open that file with something along the lines of "Show Package Contents" and locate the `Contents` folder.
3. Drag/copy `Contents` into the `x64` folder so that `Contents` and `jre.bundle` are in the same folder alongside each other.
4. Check that `~/Library/Application Support/.songsofwar/runtime/x64/Contents` actually exists as a directory.
4. Try the launcher again.

Let me know if you need help along the way, though responses might be slow as I might be busy with schoolwork. If you have Discord, [joining us](https://discord.songs-of-war.com) would help should more issues arise; we have a dedicated channel for technical help.

As it relates to the source code, I may look into a more permanent solution when I have the time and my schedule is more permissive.
